triv: fixed subject location on new images
django-cms/django-filer pull request #1276
Opened 2022-02-03 16:15 UTC by viliammihalik

## Description

* https://github.com/django-cms/django-filer/issues/1275

## Related resources

* https://github.com/django-cms/django-filer/issues/1275

## Checklist

* [x] I have opened this pull request against ``master``
* [ ] I have added or modified the tests when changing logic
* [x] I have followed [the conventional commits guidelines](https://www.conventionalcommits.org/) to add meaningful information into the changelog
* [ ] I have read the [contribution guidelines ](https://github.com/django-cms/django-filer/blob/master/docs/development.rst#contributing) and I have joined #workgroup-pr-review on 
[Slack](https://www.django-cms.org/slack) to find a “pr review buddy” who is going to review my pull request.

2022-02-05 20:47 UTC, marksweb requested changes

2022-02-05 20:47 UTC, marksweb commented on filer/admin/imageadmin.py
> +            return None
To do this, you'd need to return an empty string, not `None`, because the field is a `NOT NULL` field at the database level.

2022-02-05 20:47 UTC, marksweb commented on filer/admin/imageadmin.py
> +            return None
However having tested this, following returning an empty string there is still a test failure;

```
======================================================================
FAIL: test_image_subject_location (tests.test_admin.FilerAdminContextTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mwalker/apps/django-filer/tests/test_admin.py", line 1203, in test_image_subject_location
    do_test_image_subject_location(subject_location=subject_location)
  File "/Users/mwalker/apps/django-filer/tests/test_admin.py", line 1195, in do_test_image_subject_location
    self.assertEqual(saved_image.subject_location,
AssertionError: '' != '10,10'
```

2022-02-07 21:33 UTC, marksweb commented
Please run the tox tests to verify that tests pass.

2022-02-08 09:00 UTC, viliammihalik commented
It is still not working. I need to add it only to ImageAdmin because anywhere else it is affecting other parts of code.

2022-02-09 13:45 UTC, viliammihalik commented
@marksweb  I don't know how to fix this. There is a problem that, if you upload an image from folder admin, all images have subjection location == ''(empty string). Then if you go to detail of the image, empty input is filled by focal-point.js, and value is submitted together with an eventually new uploaded image with subject_location for old image(filled from JS). I am not able to tell at the backend if input was filled by used or by focal-point.js.

2022-08-30 17:40 UTC, closed without merging