fix: File expand url incorrect and worked not with custom image models
django-cms/django-filer pull request #1471
Opened 2024-05-19 13:43 UTC by fsbraun

## Description

Fixes #1470:

[fa385bd2b4b3022f54499bbb3c603d463f4baf2e](https://github.com/django-cms/django-filer/commit/fa385bd2b4b3022f54499bbb3c603d463f4baf2e) removed the `_view` suffix from url name leading to an empty link.

Also, if the `Image` model is replaced by a custom model, the reverse name changes, too. 

This PR moves the generation of the admin urls to the `BaseImage` model where the other admin urls are generated, sucha as `get_admin_change_url` etc.

## Related resources

* #1470
* #...

## Checklist

* [x] I have opened this pull request against ``master``
* [x] I have added or modified the tests when changing logic
* [x] I have followed [the conventional commits guidelines](https://www.conventionalcommits.org/) to add meaningful information into the changelog
* [x] I have read the [contribution guidelines ](https://github.com/django-cms/django-filer/blob/master/docs/development.rst#contributing) and I have joined #workgroup-pr-review on 
[Slack](https://www.django-cms.org/slack) to find a “pr review buddy” who is going to review my pull request.

2024-05-19 16:43 UTC, marksweb requested changes

2024-05-19 16:43 UTC, marksweb commented on tox.ini
> +    dj5main: -r tests/requirements/django-main.txt
```suggestion
    djmain: -r tests/requirements/django-main.txt
```

2024-05-19 16:44 UTC, fsbraun commented on tox.ini
> +    dj5main: -r tests/requirements/django-main.txt
🤦‍♂️

2024-05-20 14:59 UTC, fsbraun commented
@marksweb Oh dear, I fixed the typo in `tox.ini`.

2024-05-21 07:43 UTC, jrief approved these changes

2024-05-21 08:05 UTC, merged